"""
Django settings for myapp_final project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-i(@2qg^j!$k3dri8)zwy!#^q@mm+n_rt2q%%4dds#jf&n&ti)f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djoser',
    'django_filters',
    'task',
    'payment',
    'paypal',
    'subscriptions',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myapp_final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp_final.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.mysql',  # Use MySQL backend
       'NAME': 'lap_st5',  

       'HOST': '127.0.0.1',                   # Replace with your database name
       'USER': 'root',                        # Replace with your MySQL username
       'PASSWORD': '@dm1n',                   # Replace with your MySQL password                       
       'PORT': '3306',  
   }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'project_lab_st5',
#         'USER': 'postgres',
#         'PASSWORD': '12345',
#         'HOST': 'localhost',
#         'PORT': '5432'
#    }
# }
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.oracle",
#         "NAME": "localhost:1521/ORCL",
#         "USER": "django_test",
#         "PASSWORD": "123",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.AllowAny']
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# JWT Settings (optional expiration time)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
# settings.py
DJOSER = {
    # 'LOGIN_FIELD': 'username',  # can be 'email' if you want email login
    # 'USER_CREATE_PASSWORD_RETYPE': True,
    'SERIALIZERS': {
        "user_create": "task.serializers.ST5UserCreateSerializer",
        # "user_create_password_retype": "tasks.serializers.UserCreateSerializer",
        "user": "task.serializers.ST5UserSerializer",
        "current_user": "task.serializers.ST5UserSerializer",
        "token_create": "task.serializers.CustomTokenCreateSerializer",
    }
}

# email

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com" ## gmail.com
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "david4rtz@gmail.com"
EMAIL_HOST_PASSWORD = "irfx nqan blpu vkcy"
DEFAULT_FROM_EMAIL = "David_Boss"

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = "7597510445:AAHDDskdBu_3cD-FG33jbCgjQ6TaFaH4WE4"
TELEGRAM_CHAT_ID = "974832149" 

# djangostripe/settings.py
STRIPE_PUBLISHABLE_KEY = 'pk_test_51SOGTRJRipzH0QC3JCKuo1V3WVsPuROypRfkvy44mfxDRrwdYtH0diTljfdYrEl5Amt9gJlxn4UTVJEkipXvgyoU00Zi82oPxq'
STRIPE_SECRET_KEY = 'sk_test_51SOGTRJRipzH0QC3Z8KIQI8JbOzpIQA7gPrMuzO4KnkKRFx9Vvb6FCggeVVztTWoeToRqOO4athZKougkjvT7i0Q00sxpZoW7M'

# paypal
SITE_URL='http://localhost:8000'
PAYPAL_CLIENT_ID='AVBoTqNgUTDumpiaEy9pwYU_PH909VaNJHuWdACtiyzVkTnSEgwLGDDdPV8OiRpMULvNsmWb8slyI-Vk'
PAYPAL_CLIENT_SECRET='EAOk8JAoOUgT20jmrQWQQYnKPwt87S_ZRziWkl3Cun5gtxk5-VnRv8fYxJt75y0wqnB0hiftQVWp-iIV'
PAYPAL_MODE='sandbox'
PAYPAL_BASE_URL = "https://api-m.sandbox.paypal.com"  #live: https://api-m.paypal.com
PAYPAL_SUBSCRIPTION_PLAN_ID = 'P-5S0937251P8046054NELS7ZQ'
