# Generated by Django 4.2.26 on 2025-11-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
