# Generated by Django 4.2.26 on 2025-11-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_paypal_plan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='paypal_plan_id',
            new_name='paypal_subscription_id',
        ),
    ]
