# Generated by Django 4.2.26 on 2025-11-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_paypal_plan_id_subscriptionplan_paypal_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='paypal_subscription_id',
            new_name='paypal_plan_id',
        ),
    ]
