# Generated by Django 5.2.7 on 2025-11-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_alter_paypalsubscription_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalsubscription',
            name='plan_id',
            field=models.CharField(max_length=64),
        ),
    ]
